package cl.fibertrack.domain;
import cl.fibertrack.audit.AuditService; import cl.fibertrack.common.ApiException; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class InfrastructureService {
 private final JdbcClient db; private final AuditService audit; private static final List<String> COLORS=List.of("Verde","Naranjo","Azul","Café","Gris","Blanco","Rojo","Negro","Amarillo","Violeta","Rosado","Celeste");
 public InfrastructureService(JdbcClient db,AuditService audit){this.db=db;this.audit=audit;}
 public List<Map<String,Object>> projects(){return db.sql("SELECT * FROM proyectos WHERE activo ORDER BY nombre").query().listOfRows();}
 @Transactional public Map<String,Object> createProject(UUID actor,String nombre,String direccion,String comuna,String descripcion){var id=UUID.randomUUID();db.sql("INSERT INTO proyectos(id,nombre,direccion,comuna,descripcion) VALUES (:id,:n,:d,:c,:x)").param("id",id).param("n",nombre).param("d",direccion).param("c",comuna).param("x",descripcion).update();audit.record(actor,"PROYECTO_CREADO","PROYECTO",id,nombre,"OK");return db.sql("SELECT * FROM proyectos WHERE id=:id").param("id",id).query().singleRow();}
 public List<Map<String,Object>> headers(UUID project){return db.sql("SELECT c.*,count(p.id) FILTER(WHERE p.estado='OCUPADO') ocupados,count(p.id) FILTER(WHERE p.estado='RESERVADO') reservados,count(p.id) FILTER(WHERE p.estado='LIBRE') libres FROM cabeceras c LEFT JOIN puertos p ON p.cabecera_id=c.id WHERE c.proyecto_id=:id GROUP BY c.id ORDER BY c.nombre").param("id",project).query().listOfRows();}
 @Transactional public Map<String,Object> createHeader(UUID actor,UUID project,String name,int capacity){if(capacity!=94&&capacity!=144)throw bad("La capacidad debe ser 94 o 144");var id=UUID.randomUUID();db.sql("INSERT INTO cabeceras(id,proyecto_id,nombre,capacidad) VALUES(:id,:p,:n,:c)").param("id",id).param("p",project).param("n",name).param("c",capacity).update();for(int i=1;i<=capacity;i++)db.sql("INSERT INTO puertos(cabecera_id,numero) VALUES(:h,:n)").param("h",id).param("n",i).update();audit.record(actor,"CABECERA_CREADA","CABECERA",id,name,"OK");return header(id);}
 public Map<String,Object> header(UUID id){return db.sql("SELECT c.*,count(p.id) FILTER(WHERE p.estado='OCUPADO') ocupados,count(p.id) FILTER(WHERE p.estado='RESERVADO') reservados,count(p.id) FILTER(WHERE p.estado='LIBRE') libres FROM cabeceras c LEFT JOIN puertos p ON p.cabecera_id=c.id WHERE c.id=:id GROUP BY c.id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow();}
 public List<Map<String,Object>> sectors(UUID header){return db.sql("SELECT s.*,count(d.id) FILTER(WHERE d.activo) departamentos FROM sectores s LEFT JOIN departamentos d ON d.sector_id=s.id WHERE s.cabecera_id=:id AND s.activo GROUP BY s.id ORDER BY s.orden_visual,s.piso,s.lado").param("id",header).query().listOfRows();}
 @Transactional public Map<String,Object> createSector(UUID actor,UUID header,String floor,String side,List<String> numbers){if(numbers==null||numbers.isEmpty())throw bad("Debe ingresar al menos un departamento");var clean=numbers.stream().map(String::strip).toList();if(clean.stream().anyMatch(String::isBlank)||new HashSet<>(clean).size()!=clean.size())throw bad("Los departamentos no pueden estar vacíos ni duplicados");db.sql("SELECT id FROM cabeceras WHERE id=:h FOR UPDATE").param("h",header).query(UUID.class).optional().orElseThrow();int free=db.sql("SELECT count(*) FROM puertos WHERE cabecera_id=:h AND estado='LIBRE'").param("h",header).query(Integer.class).single();if(clean.size()*2>free)throw bad("Capacidad insuficiente: se requieren "+(clean.size()*2)+" puertos y hay "+free+" disponibles");var sid=UUID.randomUUID();db.sql("INSERT INTO sectores(id,cabecera_id,piso,lado) VALUES(:id,:h,:p,:l)").param("id",sid).param("h",header).param("p",floor.strip()).param("l",side.strip().toUpperCase()).update();int order=0;for(var number:clean){var did=UUID.randomUUID();db.sql("INSERT INTO departamentos(id,sector_id,numero,orden_visual) VALUES(:id,:s,:n,:o)").param("id",did).param("s",sid).param("n",number).param("o",order++).update();for(var type:List.of("OP1","OP2")){var port=db.sql("SELECT id FROM puertos WHERE cabecera_id=:h AND estado='LIBRE' ORDER BY numero FOR UPDATE SKIP LOCKED LIMIT 1").param("h",header).query(UUID.class).single();db.sql("UPDATE puertos SET estado='RESERVADO',updated_at=now() WHERE id=:id").param("id",port).update();db.sql("INSERT INTO posiciones_departamento(departamento_id,tipo,puerto_id,estado) VALUES(:d,:t,:p,'RESERVADA')").param("d",did).param("t",type).param("p",port).update();}}audit.record(actor,"SECTOR_CREADO","SECTOR",sid,"Piso "+floor+" lado "+side+", "+clean.size()+" departamentos","OK");return sector(sid);}
 public Map<String,Object> sector(UUID id){var s=new LinkedHashMap<>(db.sql("SELECT * FROM sectores WHERE id=:id").param("id",id).query().singleRow());s.put("departamentos",db.sql("SELECT d.*,json_agg(json_build_object('id',p.id,'tipo',p.tipo,'estado',p.estado,'puerto',pt.numero) ORDER BY p.tipo) posiciones FROM departamentos d JOIN posiciones_departamento p ON p.departamento_id=d.id LEFT JOIN puertos pt ON pt.id=p.puerto_id WHERE d.sector_id=:id AND d.activo GROUP BY d.id ORDER BY d.orden_visual").param("id",id).query().listOfRows());return s;}
 @Transactional public Map<String,Object> createCable(UUID actor,UUID project,String name,String code){var cid=UUID.randomUUID();db.sql("INSERT INTO cables(id,proyecto_id,nombre,codigo,cantidad_fibras) VALUES(:id,:p,:n,:c,48)").param("id",cid).param("p",project).param("n",name).param("c",code).update();int global=1;for(int tube=1;tube<=6;tube++){var tid=UUID.randomUUID();db.sql("INSERT INTO tubos(id,cable_id,numero,color) VALUES(:id,:c,:n,:color)").param("id",tid).param("c",cid).param("n",tube).param("color",COLORS.get(tube-1)).update();for(int fiber=1;fiber<=8;fiber++)db.sql("INSERT INTO fibras(tubo_id,numero_global,numero_en_tubo,color) VALUES(:t,:g,:n,:c)").param("t",tid).param("g",global++).param("n",fiber).param("c",COLORS.get(fiber-1)).update();}audit.record(actor,"CABLE_CREADO","CABLE",cid,"Cable 48 fibras","OK");return db.sql("SELECT * FROM cables WHERE id=:id").param("id",cid).query().singleRow();}
 @Transactional public void assignFiber(UUID actor,UUID position,UUID fiber,UUID operator){var used=db.sql("SELECT count(*) FROM conexiones_fibra WHERE fibra_id=:f AND activo").param("f",fiber).query(Integer.class).single();if(used>0)throw new ApiException(HttpStatus.CONFLICT,"La fibra ya tiene una asignación activa");db.sql("INSERT INTO conexiones_fibra(posicion_id,fibra_id) VALUES(:p,:f)").param("p",position).param("f",fiber).update();db.sql("UPDATE fibras SET estado='ASIGNADA',updated_at=now() WHERE id=:f").param("f",fiber).update();db.sql("UPDATE posiciones_departamento SET estado='ASIGNADA',operador_id=:o,updated_at=now() WHERE id=:p").param("o",operator).param("p",position).update();db.sql("UPDATE puertos SET estado='OCUPADO',updated_at=now() WHERE id=(SELECT puerto_id FROM posiciones_departamento WHERE id=:p)").param("p",position).update();audit.record(actor,"FIBRA_ASIGNADA","POSICION",position,"Fibra "+fiber,"OK");}
 public Map<String,Object> trace(UUID position){return db.sql("SELECT pr.nombre proyecto,c.nombre cabecera,pt.numero puerto,s.piso,s.lado,d.numero departamento,p.tipo,o.nombre operador,ca.nombre cable,t.numero tubo,f.numero_global fibra,f.color,f.estado,u.nombre||' '||u.apellido fusionador,fu.fecha fecha_fusion FROM posiciones_departamento p JOIN departamentos d ON d.id=p.departamento_id JOIN sectores s ON s.id=d.sector_id JOIN cabeceras c ON c.id=s.cabecera_id JOIN proyectos pr ON pr.id=c.proyecto_id LEFT JOIN puertos pt ON pt.id=p.puerto_id LEFT JOIN operadores o ON o.id=p.operador_id LEFT JOIN conexiones_fibra cf ON cf.posicion_id=p.id AND cf.activo LEFT JOIN fibras f ON f.id=cf.fibra_id LEFT JOIN tubos t ON t.id=f.tubo_id LEFT JOIN cables ca ON ca.id=t.cable_id LEFT JOIN fusiones fu ON fu.conexion_id=cf.id LEFT JOIN usuarios u ON u.id=fu.fusionador_id WHERE p.id=:id").param("id",position).query().listOfRows().stream().findFirst().orElseThrow();}
 private ApiException bad(String s){return new ApiException(HttpStatus.BAD_REQUEST,s);}
}
