package cl.fibertrack.domain;
import cl.fibertrack.audit.AuditService; import cl.fibertrack.common.ApiException; import cl.fibertrack.security.PrincipalUser; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/v1") public class OperationsController { private final JdbcClient db;private final AuditService audit;public OperationsController(JdbcClient db,AuditService audit){this.db=db;this.audit=audit;}
 public record Operator(@NotBlank String nombre,@NotBlank String codigo){} public record Fusion(@NotNull UUID conexionId,@NotNull UUID fibraId,String estado,String observaciones){}
 @PostMapping("/operadores") @PreAuthorize("hasAuthority('OPERADOR_CREAR') or hasAuthority('OWNER')") @Transactional Object operator(@RequestBody Operator r,@AuthenticationPrincipal PrincipalUser p){var id=UUID.randomUUID();db.sql("INSERT INTO operadores(id,nombre,codigo) VALUES(:id,:n,:c)").param("id",id).param("n",r.nombre()).param("c",r.codigo().strip().toUpperCase()).update();audit.record(p.id(),"OPERADOR_CREADO","OPERADOR",id,r.nombre(),"OK");return db.sql("SELECT * FROM operadores WHERE id=:id").param("id",id).query().singleRow();}
 @GetMapping("/proyectos/{id}/cables") @PreAuthorize("hasAuthority('CABLE_VER') or hasAuthority('OWNER')") Object cables(@PathVariable UUID id){return db.sql("SELECT * FROM cables WHERE proyecto_id=:id AND activo ORDER BY nombre").param("id",id).query().listOfRows();}
 @PostMapping("/fusiones") @PreAuthorize("hasAuthority('FUSION_CREAR') or hasAuthority('OWNER')") @Transactional Object fusion(@RequestBody Fusion r,@AuthenticationPrincipal PrincipalUser p){var active=db.sql("SELECT count(*) FROM conexiones_fibra WHERE id=:c AND fibra_id=:f AND activo").param("c",r.conexionId()).param("f",r.fibraId()).query(Integer.class).single();if(active!=1)throw new ApiException(HttpStatus.CONFLICT,"La conexión activa no corresponde a la fibra");var id=UUID.randomUUID();db.sql("INSERT INTO fusiones(id,conexion_id,fibra_id,fusionador_id,fecha,estado,observaciones) VALUES(:id,:c,:f,:u,now(),:e,:o)").param("id",id).param("c",r.conexionId()).param("f",r.fibraId()).param("u",p.id()).param("e",r.estado()==null?"REALIZADA":r.estado()).param("o",r.observaciones()).update();db.sql("UPDATE fibras SET estado='FUSIONADA',updated_at=now() WHERE id=:id").param("id",r.fibraId()).update();audit.record(p.id(),"FUSION_CREADA","FUSION",id,r.observaciones(),"OK");return db.sql("SELECT * FROM fusiones WHERE id=:id").param("id",id).query().singleRow();}
 @GetMapping("/fusiones") @PreAuthorize("hasAuthority('FUSION_VER') or hasAuthority('OWNER')") Object fusions(){return db.sql("SELECT f.*,u.nombre||' '||u.apellido fusionador FROM fusiones f JOIN usuarios u ON u.id=f.fusionador_id ORDER BY f.fecha DESC LIMIT 500").query().listOfRows();}
}
