package cl.fibertrack.auth;
import cl.fibertrack.audit.AuditService; import cl.fibertrack.common.ApiException; import cl.fibertrack.config.FiberTrackProperties; import cl.fibertrack.security.*; import cl.fibertrack.user.*; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class AuthService {
 private final UserRepository users; private final UserSessionRepository sessions; private final PasswordResetTokenRepository resets; private final PasswordEncoder passwords; private final JwtService jwt; private final FiberTrackProperties props; private final AuditService audit; private final EmailService email; private final SecureRandom random=new SecureRandom();
 @Transactional public AuthDtos.Tokens login(AuthDtos.Login r){var u=users.findByEmailIgnoreCaseAndDeletedAtIsNull(normalize(r.email())).orElseThrow(()->unauthorized()); if(!u.isActivo()||!"ACTIVA".equals(u.getCredentialStatus())||u.getPasswordHash()==null||!passwords.matches(r.password(),u.getPasswordHash())){audit.record(u.getId(),"LOGIN_FALLIDO","USUARIO",u.getId(),"Credenciales rechazadas","DENEGADO");throw unauthorized();} audit.record(u.getId(),"LOGIN","USUARIO",u.getId(),"Inicio de sesión","OK");return createSession(u,r.deviceName(),r.devicePlatform());}
 @Transactional public AuthDtos.Tokens refresh(String raw){var s=sessions.findByRefreshTokenHashAndRevokedAtIsNull(hash(raw)).orElseThrow(()->unauthorized()); if(s.getExpiresAt().isBefore(Instant.now())||!s.getUser().isActivo()){s.setRevokedAt(Instant.now());throw unauthorized();} s.setLastUsedAt(Instant.now()); return new AuthDtos.Tokens(jwt.issue(PrincipalUser.from(s.getUser())),raw,jwt.expiresIn(),view(s.getUser()));}
 @Transactional public void logout(UUID userId,String raw){sessions.findByRefreshTokenHashAndRevokedAtIsNull(hash(raw)).filter(s->s.getUser().getId().equals(userId)).ifPresent(s->s.setRevokedAt(Instant.now()));audit.record(userId,"LOGOUT","USER_SESSION",null,"Cierre de sesión","OK");}
 @Transactional public String requestPassword(String address){users.findByEmailIgnoreCaseAndDeletedAtIsNull(normalize(address)).filter(User::isActivo).ifPresent(u->{resets.findByUserIdAndUsedAtIsNullAndRevokedAtIsNull(u.getId()).forEach(t->t.setRevokedAt(Instant.now()));var raw=randomToken();var t=new PasswordResetToken();t.setUser(u);t.setTokenHash(hash(raw));t.setExpiresAt(Instant.now().plus(Duration.ofMinutes(30)));resets.save(t);email.sendPasswordReset(u.getEmail(),raw);audit.record(u.getId(),"PASSWORD_RESET_SOLICITADO","USUARIO",u.getId(),"Solicitud creada","OK");});return "Si el correo está registrado en FiberTrack, recibirás instrucciones.";}
 @Transactional public void resetPassword(String raw,String password){validatePassword(password);var t=resets.findByTokenHashAndUsedAtIsNullAndRevokedAtIsNull(hash(raw)).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"Token inválido o expirado"));var u=t.getUser();u.setPasswordHash(passwords.encode(password));u.setCredentialStatus("ACTIVA");t.setUsedAt(Instant.now());sessions.findByUserIdAndRevokedAtIsNull(u.getId()).forEach(s->s.setRevokedAt(Instant.now()));audit.record(u.getId(),"PASSWORD_RESTABLECIDA","USUARIO",u.getId(),"Credencial actualizada y sesiones revocadas","OK");}
 @Transactional public void changePassword(User u,String current,String next){if(!passwords.matches(current,u.getPasswordHash()))throw new ApiException(HttpStatus.BAD_REQUEST,"Contraseña actual incorrecta");validatePassword(next);u.setPasswordHash(passwords.encode(next));sessions.findByUserIdAndRevokedAtIsNull(u.getId()).forEach(s->s.setRevokedAt(Instant.now()));audit.record(u.getId(),"PASSWORD_CAMBIADA","USUARIO",u.getId(),"Credencial actualizada","OK");}
 private AuthDtos.Tokens createSession(User u,String name,String platform){var raw=randomToken();var s=new UserSession();s.setId(UUID.randomUUID());s.setUser(u);s.setRefreshTokenHash(hash(raw));s.setExpiresAt(Instant.now().plusSeconds(props.jwt().refreshSeconds()));s.setLastUsedAt(Instant.now());s.setDeviceName(name);s.setDevicePlatform(platform);sessions.save(s);return new AuthDtos.Tokens(jwt.issue(PrincipalUser.from(u)),raw,jwt.expiresIn(),view(u));}
 public AuthDtos.UserView view(User u){return new AuthDtos.UserView(u.getId(),u.getNombre(),u.getApellido(),u.getEmail(),u.isOwner(),u.getRoles().stream().map(Role::getCodigo).collect(java.util.stream.Collectors.toSet()),u.effectivePermissions());}
 private String randomToken(){byte[] b=new byte[48];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}} private String normalize(String e){return e.strip().toLowerCase(Locale.ROOT);} private ApiException unauthorized(){return new ApiException(HttpStatus.UNAUTHORIZED,"Credenciales inválidas");} private void validatePassword(String p){if(p==null||p.length()<10||!p.matches(".*[A-Z].*")||!p.matches(".*[a-z].*")||!p.matches(".*[0-9].*"))throw new ApiException(HttpStatus.BAD_REQUEST,"La contraseña debe tener 10 caracteres, mayúscula, minúscula y número");}
}
