package cl.fibertrack.certification;
import cl.fibertrack.security.PrincipalUser; import jakarta.validation.constraints.*; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/certificaciones") @RequiredArgsConstructor public class CertificationController {
 private final CertificationService service; public record Create(@NotNull UUID proyectoId,@NotNull UUID cabeceraId,@NotNull UUID sectorId,String observaciones){} public record Measurement(@NotNull UUID departamentoId,@Pattern(regexp="OP1|OP2") String operadorPosicion,@Pattern(regexp="1310|1490|1550|LOG") String longitudOnda,Double valor,boolean log,String observacion){}
 @GetMapping @PreAuthorize("hasAuthority('CERTIFICACION_VER') or hasAuthority('OWNER')") Object list(){return service.list();}
 @PostMapping @PreAuthorize("hasAuthority('CERTIFICACION_CREAR') or hasAuthority('OWNER')") Object create(@RequestBody Create r,@AuthenticationPrincipal PrincipalUser p){return service.create(p.id(),r.proyectoId,r.cabeceraId,r.sectorId,r.observaciones);}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('CERTIFICACION_VER') or hasAuthority('OWNER')") Object get(@PathVariable UUID id){return service.get(id);}
 @PutMapping("/{id}/mediciones") @PreAuthorize("hasAuthority('MEDICION_CREAR') or hasAuthority('MEDICION_EDITAR') or hasAuthority('OWNER')") void measure(@PathVariable UUID id,@RequestBody Measurement r,@AuthenticationPrincipal PrincipalUser p){service.measurement(p.id(),id,r.departamentoId,r.operadorPosicion,r.longitudOnda,r.valor,r.log,r.observacion);}
 @PostMapping("/{id}/aprobar") @PreAuthorize("hasAuthority('CERTIFICACION_APROBAR') or hasAuthority('OWNER')") void approve(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser p){service.transition(p.id(),id,"APROBADA");}
 @PostMapping("/{id}/rechazar") @PreAuthorize("hasAuthority('CERTIFICACION_RECHAZAR') or hasAuthority('OWNER')") void reject(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser p){service.transition(p.id(),id,"RECHAZADA");}
 @PostMapping("/{id}/anular") @PreAuthorize("hasAuthority('CERTIFICACION_ANULAR') or hasAuthority('OWNER')") void voidCert(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser p){service.transition(p.id(),id,"ANULADA");}
 @GetMapping(value="/{id}/pdf",produces=MediaType.APPLICATION_PDF_VALUE) @PreAuthorize("hasAuthority('CERTIFICACION_PDF_VER') or hasAuthority('CERTIFICACION_PDF_GENERAR') or hasAuthority('OWNER')") ResponseEntity<byte[]> pdf(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser p){var c=service.get(id);return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=FiberTrack_"+c.get("numero_certificacion")+".pdf").body(service.pdf(p.id(),id));}
}
