package cl.fibertrack.certification;
import cl.fibertrack.audit.AuditService; import cl.fibertrack.common.ApiException; import org.apache.pdfbox.pdmodel.*; import org.apache.pdfbox.pdmodel.common.PDRectangle; import org.apache.pdfbox.pdmodel.font.*; import org.springframework.http.HttpStatus; import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.io.*; import java.time.*; import java.util.*;
@Service public class CertificationService {
 private final JdbcClient db; private final AuditService audit; public CertificationService(JdbcClient db,AuditService audit){this.db=db;this.audit=audit;}
 public List<Map<String,Object>> list(){return db.sql("SELECT c.id,c.numero_certificacion,c.estado,c.fecha_certificacion,p.nombre proyecto,h.nombre cabecera,s.piso,s.lado FROM certificaciones c JOIN proyectos p ON p.id=c.proyecto_id JOIN cabeceras h ON h.id=c.cabecera_id JOIN sectores s ON s.id=c.sector_id ORDER BY c.created_at DESC").query().listOfRows();}
 @Transactional public Map<String,Object> create(UUID actor,UUID project,UUID header,UUID sector,String observations){var id=UUID.randomUUID();db.sql("INSERT INTO certificaciones(id,proyecto_id,cabecera_id,sector_id,certificador_id,observaciones) VALUES(:id,:p,:h,:s,:u,:o)").param("id",id).param("p",project).param("h",header).param("s",sector).param("u",actor).param("o",observations).update();audit.record(actor,"CERTIFICACION_CREADA","CERTIFICACION",id,"Borrador","OK");return get(id);}
 public Map<String,Object> get(UUID id){var row=db.sql("SELECT c.*,p.nombre proyecto,p.direccion,h.nombre cabecera,s.piso,s.lado,u.nombre||' '||u.apellido certificador FROM certificaciones c JOIN proyectos p ON p.id=c.proyecto_id JOIN cabeceras h ON h.id=c.cabecera_id JOIN sectores s ON s.id=c.sector_id JOIN usuarios u ON u.id=c.certificador_id WHERE c.id=:id").param("id",id).query().listOfRows().stream().findFirst().orElseThrow();var out=new LinkedHashMap<>(row);out.put("mediciones",db.sql("SELECT m.*,d.numero departamento FROM mediciones m JOIN departamentos d ON d.id=m.departamento_id WHERE m.certificacion_id=:id ORDER BY d.orden_visual,m.operador_posicion,m.longitud_onda").param("id",id).query().listOfRows());return out;}
 @Transactional public void measurement(UUID actor,UUID cert,UUID department,String op,String wave,Double value,boolean log,String note){ensureEditable(cert);db.sql("INSERT INTO mediciones(certificacion_id,departamento_id,operador_posicion,longitud_onda,valor,log,observacion,tecnico_id) VALUES(:c,:d,:o,:w,:v,:l,:n,:u) ON CONFLICT(certificacion_id,departamento_id,operador_posicion,longitud_onda) DO UPDATE SET valor=excluded.valor,log=excluded.log,observacion=excluded.observacion,tecnico_id=excluded.tecnico_id,updated_at=now()").param("c",cert).param("d",department).param("o",op).param("w",wave).param("v",value).param("l",log).param("n",note).param("u",actor).update();audit.record(actor,"MEDICION_EDITADA","CERTIFICACION",cert,department+" "+op+" "+wave,"OK");}
 @Transactional public void transition(UUID actor,UUID id,String state){var current=db.sql("SELECT estado FROM certificaciones WHERE id=:id FOR UPDATE").param("id",id).query(String.class).optional().orElseThrow();if("APROBADA".equals(current)||"ANULADA".equals(current))throw new ApiException(HttpStatus.CONFLICT,"La certificación cerrada no puede modificarse silenciosamente");String sql=switch(state){case "APROBADA"->"UPDATE certificaciones SET estado='APROBADA',aprobado_por=:u,fecha_aprobacion=now(),updated_at=now() WHERE id=:id";case "RECHAZADA"->"UPDATE certificaciones SET estado='RECHAZADA',rechazado_por=:u,fecha_rechazo=now(),updated_at=now() WHERE id=:id";case "ANULADA"->"UPDATE certificaciones SET estado='ANULADA',anulado_por=:u,fecha_anulacion=now(),updated_at=now() WHERE id=:id";default->throw new IllegalArgumentException();};db.sql(sql).param("u",actor).param("id",id).update();audit.record(actor,"CERTIFICACION_"+state,"CERTIFICACION",id,"Estado "+state,"OK");}
 public byte[] pdf(UUID actor,UUID id){var c=get(id);try(var doc=new PDDocument();var out=new ByteArrayOutputStream()){var rows=(List<Map<String,Object>>)c.get("mediciones");int index=0,pageNo=1;do{var page=new PDPage(PDRectangle.A4);doc.addPage(page);try(var cs=new PDPageContentStream(doc,page)){var bold=new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);var normal=new PDType1Font(Standard14Fonts.FontName.HELVETICA);text(cs,bold,16,45,800,"FIBERTRACK - CERTIFICACIÓN DE FIBRA ÓPTICA");text(cs,normal,10,45,780,"N° "+c.get("numero_certificacion")+"   Estado: "+c.get("estado"));text(cs,normal,10,45,765,"Proyecto: "+c.get("proyecto")+"   Cabecera: "+c.get("cabecera"));text(cs,normal,10,45,750,"Piso: "+c.get("piso")+"   Lado: "+c.get("lado")+"   Certificador: "+c.get("certificador"));text(cs,bold,9,45,725,"DEPTO     POSICIÓN     LONGITUD     VALOR     UNIDAD     LOG");float y=708;int count=0;while(index<rows.size()&&count<35){var r=rows.get(index++);text(cs,normal,9,45,y,String.format("%-12s %-14s %-14s %-12s %-10s %s",r.get("departamento"),r.get("operador_posicion"),r.get("longitud_onda"),Objects.toString(r.get("valor"),"-"),r.get("unidad"),r.get("log")));y-=17;count++;}text(cs,normal,8,45,35,"FiberTrack • "+c.get("numero_certificacion")+" • Página "+pageNo);pageNo++;}}while(index<rows.size());doc.save(out);audit.record(actor,"PDF_GENERADO","CERTIFICACION",id,"PDF oficial","OK");return out.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
 private void text(PDPageContentStream cs,PDFont f,float size,float x,float y,String text)throws IOException{cs.beginText();cs.setFont(f,size);cs.newLineAtOffset(x,y);cs.showText(text.replaceAll("[^\\x20-\\x7EáéíóúÁÉÍÓÚñÑ°•]",""));cs.endText();}
 private void ensureEditable(UUID id){var s=db.sql("SELECT estado FROM certificaciones WHERE id=:id").param("id",id).query(String.class).optional().orElseThrow();if(!Set.of("BORRADOR","FINALIZADA","RECHAZADA").contains(s))throw new ApiException(HttpStatus.CONFLICT,"La certificación no es editable");}
}
