package cl.fibertrack.user;
import cl.fibertrack.audit.AuditService; import cl.fibertrack.auth.AuthService; import cl.fibertrack.common.ApiException; import cl.fibertrack.security.PrincipalUser; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/usuarios") @RequiredArgsConstructor public class UserAdminController {
 private final UserRepository users; private final RoleRepository roles; private final PermissionRepository permissions; private final AuthService auth; private final AuditService audit;
 public record Create(@NotBlank String nombre,@NotBlank String apellido,@Email @NotBlank String email,boolean activo,Set<String> roles,Set<String> permisos){}
 public record Access(Set<String> roles,Set<String> permisos){}
 @GetMapping @PreAuthorize("hasAuthority('USUARIO_VER') or hasAuthority('OWNER')") List<?> all(){return users.findAll().stream().filter(u->u.getDeletedAt()==null).map(auth::view).toList();}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasAuthority('USUARIO_CREAR') or hasAuthority('OWNER')") @Transactional Object create(@Valid @RequestBody Create r,@AuthenticationPrincipal PrincipalUser actor){var email=r.email().strip().toLowerCase(Locale.ROOT);if(users.existsByEmailIgnoreCaseAndDeletedAtIsNull(email))throw new ApiException(HttpStatus.CONFLICT,"El correo ya está registrado");var u=new User();u.setNombre(r.nombre().strip());u.setApellido(r.apellido().strip());u.setEmail(email);u.setActivo(r.activo());u.setCredentialStatus("PENDIENTE");if(r.roles()!=null)r.roles().forEach(code->roles.findByCodigo(code).ifPresent(u.getRoles()::add));if(r.permisos()!=null)u.getPermissions().addAll(permissions.findByCodigoIn(r.permisos()));users.save(u);audit.record(actor.id(),"USUARIO_CREADO","USUARIO",u.getId(),"Usuario creado sin contraseña","OK");return auth.view(u);}
 @PostMapping("/{id}/desactivar") @PreAuthorize("hasAuthority('USUARIO_DESACTIVAR') or hasAuthority('OWNER')") @Transactional void deactivate(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser actor){var u=users.findById(id).orElseThrow();protect(u,actor,"INTENTO_DESACTIVAR_OWNER");u.setActivo(false);audit.record(actor.id(),"USUARIO_DESACTIVADO","USUARIO",id,"Usuario desactivado","OK");}
 @PutMapping("/{id}/accesos") @PreAuthorize("hasAuthority('ROL_ASIGNAR') or hasAuthority('PERMISO_ASIGNAR') or hasAuthority('OWNER')") @Transactional Object access(@PathVariable UUID id,@RequestBody Access r,@AuthenticationPrincipal PrincipalUser actor){var u=users.findById(id).orElseThrow();protect(u,actor,"INTENTO_MODIFICAR_OWNER");var requested=r.roles()==null?Set.<String>of():r.roles();if(requested.contains("ADMIN")&&!actor.owner()&&actor.authorities().stream().noneMatch(a->a.getAuthority().equals("ADMIN_CREAR")))throw new ApiException(HttpStatus.FORBIDDEN,"No posee permiso para asignar ADMIN");u.getRoles().clear();requested.forEach(code->roles.findByCodigo(code).ifPresent(u.getRoles()::add));u.getPermissions().clear();if(r.permisos()!=null)u.getPermissions().addAll(permissions.findByCodigoIn(r.permisos()));audit.record(actor.id(),"ACCESOS_USUARIO_EDITADOS","USUARIO",id,"Roles y permisos actualizados","OK");return auth.view(u);}
 @DeleteMapping("/{id}") @PreAuthorize("hasAuthority('USUARIO_ELIMINAR') or hasAuthority('OWNER')") @Transactional void delete(@PathVariable UUID id,@AuthenticationPrincipal PrincipalUser actor){var u=users.findById(id).orElseThrow();protect(u,actor,"INTENTO_ELIMINAR_OWNER");u.setActivo(false);u.setDeletedAt(java.time.Instant.now());audit.record(actor.id(),"USUARIO_ELIMINADO","USUARIO",id,"Soft delete","OK");}
 private void protect(User target,PrincipalUser actor,String action){if(target.isOwner()||target.isProtectedAccount()){audit.record(actor.id(),action,"USUARIO",target.getId(),"Operación protegida rechazada","DENEGADO");throw new ApiException(HttpStatus.FORBIDDEN,"La cuenta OWNER está protegida");}}
}
